name: quickstart-flutter
repository: https://github.com/firebase/quickstart-flutter

packages:
- authentication/**
- crashlytics/**
- firestore/**
- remote_config/**
- storage/**

scripts:
  analyze: melos exec -- "dart analyze ."

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
